

# 服务器配置
server:
  port: 8080
management:
  context-path: /management
  health:
    mail:
      enabled: false

endpoints:
  shutdown:
    enabled: true
    sensitive: true

security:
  user:
    name: admin
    password: 123456